spring:
  rabbitmq:
    host: localhost  # ip???????????
    port: 5672 # ?????????15672????????
    username: study # ????????
    password: study #??
    virtual-host: /study # ????
    publisher-confirm-type: correlated #??????
    publisher-returns: true # ??return??
