spring:
  rabbitmq:
    host: localhost  # ip???????????
    port: 5672 # ?????????15672????????
    username: study # ????????
    password: study #??
    virtual-host: /study # ????
    listener:
      direct:
        acknowledge-mode: manual #??????
        prefetch: 1
